name: Setup Digital Ocean Client for Kubernetes Cluster

on:
  workflow_call:
    # Required
    inputs:
      environment:
        type: string
        required: true

jobs:
  setup-digital-ocean-client:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save  --expiry-seconds 600 ${{ vars.CLUSTER_NAME }}